### ISSUE TITLE
Custom Metadata

### ISSUE THREAD

**Issue by simonmorley** [chef/knife-google#37]
According to the help for the create server actions, we can add custom metadata to the servers.

I've tried this options:

```--gce-metadata startup-script-url=http://storage.googleapis.com/ps_startup_scripts/startup.sh \
``

Which looks ok, but nothing's added to the VM. The tests actually look like this should be just 'metadata'.

Maybe I'm wrong, could someone suggest the correct syntax for this.

**Comment by Aliasgar16** [comment]
Could you please provide the knife-google version number from which you are trying the operation.

**Comment by Aliasgar16** [comment]
Hi @simonmorley 

We tested the --gce-metadata option by providing a URL for a sample starter-script and it's working fine. All key-value pairs passed through --gce-metadata option gets added under custom metadata section of the particular VM. Script may fail due to following reasons:
1. Script is inaccessible.
2. Script is itself failing.

If you are putting your starter-script at Google Cloud Storage, please make sure you give proper access rights to your script stored in the bucket and public URL is to be used.

Command used by us:

bundle exec knife google server create <vm_name> -m <machine_type> -I <image_name> -Z <zone_name> -x <user_name> -i <identity_file_absolute_path> --gce-metadata "startup-script-url=<startup_script_url>" -VV

In case you still face difficulty, please share following logs:
/var/log/startupscript.log 
/var/run/google.startup.script 
/var/log/google.log 

Note: we used knife-google 1.4.3

**Comment by NimishaS** [comment]
This has been resolved as a part of https://github.com/chef/knife-google/issues/74. Issues doesn't seem to persist.
