### ISSUE TITLE
Feature Request: lists for additional assets

### ISSUE THREAD

**Issue by yonah-codefresh** [chef/knife-google#73]
Would be nice to have a way to list additional assets, specifically:
* Images
* Machine types
* Networks
* Static IP addresses

**Comment by adamleff** [comment]
@yonah-codefresh thanks for your suggestion. I'm not sure if we will implement these features since it's incredibly easy to list the same information using the Google Cloud SDK (`gcloud compute machine-types list`, for example), and we now use the Google Cloud SDK credentials in knife to authenticate you as a GCP user, so there's no benefit to having this information in knife.

However, if you'd like to implement it, we will happily take a look at a pull request!
